services:
  dev:
    image: node:22
    working_dir: /workspace
    volumes:
      - .:/workspace
      - pnpm-store:/root/.local/share/pnpm/store/v3
    environment:
      PNPM_HOME: /root/.local/share/pnpm
      PATH: /root/.local/share/pnpm:$PATH
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "true"
    command: >
      sh -lc "
        corepack enable &&
        pnpm install &&
        pnpm dev
      "
    ports:
      - "3000:3000" # client
      - "3010:3010" # api

volumes:
  pnpm-store:
