version: "3.8"
services:
  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env
    ports:
      - "3010:3010"
    restart: unless-stopped
    depends_on:
      - web
  web:
    build: ./apps/web
    env_file:
      - ./apps/web/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - api
